CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'BUYER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- F1: Admin, Seller மற்றும் Buyer கணக்குகளை BCrypt hash மூலம் Seed செய்தல்
-- admin கடவுச்சொல்: admin123
-- seller1 கடவுச்சொல்: seller123
-- buyer1 கடவுச்சொல்: buyer123
MERGE INTO users (username, password_hash, email, role)
KEY(username)
VALUES 
('admin', '$2a$12$t7S16S/Gz8onn9Bo31LlyeIrXWMJJlE0F2HaSkDv22hBylqyToPE6', 'admin@thabithamart.com', 'ADMIN'),
('seller1', '$2a$12$8K1p/a0dL1LXMIgoEDFrwOdgqT0Gvh.Q8xo6N5vKz0r51Vn7p7yG2', 'seller@thabithamart.com', 'SELLER'),
('buyer1', '$2a$12$e0MYzX1Wq8rU8gA9L5YJ.O7MvQ5G3d2n5K8R6W9Z2y4x7v0u1s3tG', 'buyer@thabithamart.com', 'BUYER');

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    image_url VARCHAR(500),
    description VARCHAR(500)
);

MERGE INTO products(name, category, price, stock, image_url, description)
KEY(name)
VALUES
('Classic Black T-Shirt', 'Men', 499.00, 25, 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&q=80', '100% pure cotton breathable everyday black wear'),
('Slim Fit Denim Jeans', 'Men', 1299.00, 18, 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&q=80', 'Stretchable comfortable blue denim jeans'),
('Casual Linen Shirt', 'Men', 899.00, 15, 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&q=80', 'Full-sleeve formal and casual wear shirt'),
('Black Fleece Hoodie', 'Men', 1499.00, 12, 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&q=80', 'Warm fleece oversized winter wear hoodie'),
('Formal Party Blazer', 'Men', 3499.00, 8, 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500&q=80', 'Premium slim-fit stylish blazer for events'),
('Sporty Track Pants', 'Men', 699.00, 20, 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500&q=80', 'Quick-dry activewear track pants for gym & run'),
('Striped Polo T-Shirt', 'Men', 749.00, 16, 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500&q=80', 'Collared premium polo shirt for weekend outings'),
('Leather Bomber Jacket', 'Men', 2899.00, 10, 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&q=80', 'Classic vintage black faux leather jacket');

ALTER TABLE products ADD COLUMN IF NOT EXISTS seller_id BIGINT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP;