CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    image_url VARCHAR(500),
    description VARCHAR(500)
);
MERGE INTO products(name, category, price, stock, image_url, description)
KEY(name)
VALUES
('Classic T-Shirt', 'Men', 599.00, 20, '', 'Comfortable cotton T-Shirt'),

('Denim Jeans', 'Men', 1299.00, 15, '', 'Premium denim jeans'),

('Casual Shirt', 'Men', 899.00, 12, '', 'Stylish casual shirt'),

('Floral Dress', 'Women', 999.00, 10, '', 'Elegant floral dress'),

('Women Kurti', 'Women', 799.00, 25, '', 'Comfortable designer kurti'),

('Handbag', 'Women', 699.00, 18, '', 'Modern everyday handbag');