CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'BUYER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- F1: Seed Admin, Seller and Buyer accounts with BCrypt hashed passwords
-- admin password:   admin123
-- seller1 password: seller123
-- buyer1 password:  buyer123
MERGE INTO users (username, password_hash, email, role)
KEY(username)
VALUES 
('admin', '$2a$12$t7S16S/Gz8onn9Bo31LlyeIrXWMJJlE0F2HaSkDv22hBylqyToPE6', 'admin@thabithamart.com', 'ADMIN'),
('seller1', '$2a$12$8K1p/a0dL1LXMIgoEDFrwOdgqT0Gvh.Q8xo6N5vKz0r51Vn7p7yG2', 'seller@thabithamart.com', 'SELLER'),
('buyer1', '$2a$12$e0MYzX1Wq8rU8gA9L5YJ.O7MvQ5G3d2n5K8R6W9Z2y4x7v0u1s3tG', 'buyer@thabithamart.com', 'BUYER');

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    image_url VARCHAR(500),
    description VARCHAR(500)
);

INSERT INTO products(name, category, price, stock, image_url, description)
SELECT * FROM (VALUES
('Classic Black T-Shirt', 'Men', 499.00, 25, 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&q=80', '100% pure cotton breathable everyday black wear'),
('Slim Fit Denim Jeans', 'Men', 1299.00, 18, 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&q=80', 'Stretchable comfortable blue denim jeans'),
('Casual Linen Shirt', 'Men', 899.00, 15, 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&q=80', 'Full-sleeve formal and casual wear shirt'),
('Black Fleece Hoodie', 'Men', 1499.00, 12, 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&q=80', 'Warm fleece oversized winter wear hoodie'),
('Formal Party Blazer', 'Men', 3499.00, 8, 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500&q=80', 'Premium slim-fit stylish blazer for events'),
('Sporty Track Pants', 'Men', 699.00, 20, 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500&q=80', 'Quick-dry activewear track pants for gym & run'),
('Striped Polo T-Shirt', 'Men', 749.00, 16, 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500&q=80', 'Collared premium polo shirt for weekend outings'),
('Leather Bomber Jacket', 'Men', 2899.00, 10, 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&q=80', 'Classic vintage black faux leather jacket');
) AS v(name, category, price, stock, image_url, description)
WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = v.name);
ALTER TABLE products ADD COLUMN IF NOT EXISTS seller_id BIGINT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP;

-- Product specifications shown on the cart page
ALTER TABLE products ADD COLUMN IF NOT EXISTS material VARCHAR(100) DEFAULT 'Cotton blend';
ALTER TABLE products ADD COLUMN IF NOT EXISTS color VARCHAR(50) DEFAULT 'Assorted';

-- Cart: one row per user + product + size (same product in a different size is a separate row)
CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    size VARCHAR(10) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, product_id, size),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Wishlist: one row per user + product
CREATE TABLE IF NOT EXISTS wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, product_id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- ===================== NEW =====================

-- NEW: extra user details for the registration form (F1)
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile VARCHAR(20);

-- NEW: created_at on products (spec: every table)
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- NEW: orders (F5, F6, O2 status workflow)
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_order_status CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
    FOREIGN KEY (buyer_id) REFERENCES users(id)
);

-- NEW: order_items (keeps name and price at time of purchase)
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT,
    product_name VARCHAR(150) NOT NULL,
    size VARCHAR(10),
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

-- NEW: reviews (F8), one review per buyer per product
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INT NOT NULL,
    comment VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5),
    UNIQUE (product_id, user_id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- NEW: foreign keys on existing tables
ALTER TABLE products ADD CONSTRAINT IF NOT EXISTS fk_products_seller
    FOREIGN KEY (seller_id) REFERENCES users(id);
ALTER TABLE cart_items ADD CONSTRAINT IF NOT EXISTS fk_cart_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE wishlist_items ADD CONSTRAINT IF NOT EXISTS fk_wishlist_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- NEW: indexes on foreign keys and search columns
CREATE INDEX IF NOT EXISTS idx_products_seller   ON products(seller_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_name     ON products(name);
CREATE INDEX IF NOT EXISTS idx_cart_user         ON cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_product      ON cart_items(product_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_user     ON wishlist_items(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_buyer      ON orders(buyer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status     ON orders(status);
CREATE INDEX IF NOT EXISTS idx_items_order       ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_items_product     ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product   ON reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user      ON reviews(user_id);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_name VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_address VARCHAR(300);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ship_mobile VARCHAR(15);